import pandas as pd
import numpy as np

def fuente_mercadolaboral():
    f = {'Indicador': {0: 'Informalidad',
  1: 'Informalidad',
  2: 'Informalidad',
  3: 'Informalidad',
  4: 'Informalidad',
  5: 'Informalidad',
  6: 'Informalidad',
  7: 'Informalidad',
  8: 'Desempleo_por_region',
  9: 'Desempleo_por_region',
  10: 'Desempleo_por_sexo',
  11: 'Desempleo_por_sexo',
  12: 'Desempleo_por_sexo',
  13: 'Desempleo_por_sexo',
  14: 'Desempleo_por_sexo',
  15: 'Desempleo_por_sexo',
  16: 'Desempleo_por_sexo',
  17: 'Desempleo_por_sexo',
  18: 'Desempleo_desestacionalizado',
  19: 'Desempleo_desestacionalizado',
  20: 'Desempleo_estacionalizado',
  21: 'Desempleo_estacionalizado',
  22: 'Desempleo_estacionalizado',
  23: 'Desempleo_estacionalizado',
  24: 'Desempleo_estacionalizado',
  25: 'Desempleo_estacionalizado',
  26: 'Desempleo_estacionalizado'},
 'Frecuencia': {0: 'Trimestre Móvil Estacionalizado',
  1: 'Trimestre Móvil Estacionalizado',
  2: 'Trimestre Móvil Estacionalizado',
  3: 'Trimestre Móvil Estacionalizado',
  4: 'Trimestre Móvil Estacionalizado',
  5: 'Trimestre Móvil Estacionalizado',
  6: 'Trimestre Móvil Estacionalizado',
  7: 'Trimestre Móvil Estacionalizado',
  8: 'Semestral',
  9: 'Semestral',
  10: 'Trimestre Móvil Estacionalizado',
  11: 'Mensual Desetacionalizado',
  12: 'Trimestre Móvil Estacionalizado',
  13: 'Trimestre Móvil Estacionalizado',
  14: 'Trimestre Móvil Estacionalizado',
  15: 'Trimestre Móvil Desetacionalizado',
  16: 'Trimestre Móvil Estacionalizado',
  17: 'Trimestre Móvil Estacionalizado',
  18: 'Trimestre Móvil Desetacionalizado',
  19: 'Mensual Desetacionalizado',
  20: 'Trimestre Móvil Estacionalizado',
  21: 'Trimestre Móvil Estacionalizado',
  22: 'Trimestre Móvil Estacionalizado',
  23: 'Trimestre Móvil Estacionalizado',
  24: 'Trimestre Móvil Estacionalizado',
  25: 'Trimestre Móvil Estacionalizado',
  26: 'Trimestre Móvil Estacionalizado'},
 'Serie': {0: 'MLI_CII',
  1: 'MLI_CIU',
  2: 'MLI_EDU',
  3: 'MLI_PSC',
  4: 'MLI_SEX',
  5: 'MLI_SSC',
  6: 'MLI_SSP',
  7: 'MLI_TNN',
  8: 'MLR_TRC',
  9: 'MLR_TRN',
  10: 'MLS_ISS',
  11: 'MLS_MSD',
  12: 'MLS_OSO',
  13: 'MLS_OSR',
  14: 'MLS_TSC',
  15: 'MLS_TSD',
  16: 'MLS_TSN',
  17: 'MLS_TSR',
  18: 'MLD_TCR',
  19: 'MLD_TNN',
  20: 'MLE_OPC',
  21: 'MLE_OPD',
  22: 'MLE_ORC',
  23: 'MLE_ORD',
  24: 'MLE_TAC',
  25: 'MLE_TCR',
  26: 'MLE_TNN'},
 'Nombre': {0: 'ramas_ciiu4',
  1: 'ciudades',
  2: 'educacion',
  3: 'posicion_ocupacional',
  4: 'sexo',
  5: 'seguridad_social_cantidad_personas',
  6: 'seguridad_social_porcentaje_personas',
  7: 'tasa_total_nacional',
  8: 'total_cabeceras',
  9: 'total_regiones',
  10: 'inactivos_sexo',
  11: 'mensual_desetacionalizado',
  12: 'posicion_ocupacional',
  13: 'ramas_ciiu4',
  14: 'total_cabeceras',
  15: 'trimestremovil_desetacionalizado',
  16: 'total_nacional',
  17: 'total_resto',
  18: 'total_nacional_cabeceras_resto',
  19: 'total_nacional',
  20: 'ocupados_posicion_ocupacional_ciudades',
  21: 'ocupados_posicion_ocupacional_divisiones',
  22: 'estacionalizado_ocupados_ramas_ciudades',
  23: 'ocupados_ramas_divisiones',
  24: 'total_areas_ciudades',
  25: 'total_nacional_cabeceras_resto',
  26: 'total_nacional'},
 'Descripción': {0: 'Población ocupada total, informal y formal para tamaño de empresa hasta 5 trabajadores según rama de actividad CIIU 4 A.C, Series trimestre móvil ',
  1: 'Población ocupada total, informal y formal para empresas hasta 5 trabajadores según ciudad',
  2: 'Población ocupada total, informal y formal para tamaño de empresa hasta 5 trabajadores según nivel educativo',
  3: 'Población ocupada total, informal y formal para tamaño de empresa hasta 5 trabajadores según posición ocupacional',
  4: 'Población ocupada total, informal y formal para empresas hasta 5 trabajadores según sexo',
  5: 'Ocupados por afiliación a la seguridad, según régimen y pensiones.',
  6: 'Distribución porcentual de los ocupados  afiliados a seguridad social en salud (según régimen) y en pensiones.',
  7: 'Proporción de informalidad según tamaño de empresa hasta 5 trabajadores',
  8: '% población en edad de trabajar, tasa global de participación, de ocupación, de desempleo (abierto y oculto) y de subempleo. Población total, en edad de trabajar, económicamente activa, ocupados, desocupados (abiertos y ocultos), inactivos y subempleados.',
  9: '% población en edad de trabajar, tasa global de participación, de ocupación, de desempleo (abierto y oculto) y de subempleo. Población total, en edad de trabajar, económicamente activa, ocupados, desocupados (abiertos y ocultos), inactivos y subempleados.',
  10: 'Población inactiva según sexo y tipo de inactividad',
  11: '%tasa global de participación, de ocupación y desempleo. Ocupados, desocupados e inactivos. ',
  12: 'Población ocupada según sexo y posición ocupacional',
  13: 'Población ocupada según sexo y ramas de actividad',
  14: '% población en edad de trabajar, tasa global de participación, de ocupación, de desempleo (abierto y oculto) y de subempleo. Población total, en edad de trabajar, económicamente activa, ocupados, desocupados (abiertos y ocultos), inactivos y subempleados, según sexoTotal Cabeceras',
  15: '%tasa global de participación, de ocupación y desempleo.Ocupados, desocupados e inactivos. ',
  16: '% población en edad de trabajar, tasa global de participación, de ocupación, de desempleo (abierto y oculto) y de subempleo.Población total, en edad de trabajar, económicamente activa, ocupados, desocupados (abiertos y ocultos), inactivos y subempleados, según sexo Total Nacional',
  17: '% población en edad de trabajar, tasa global de participación, de ocupación, de desempleo (abierto y oculto) y de subempleo.Población total, en edad de trabajar, económicamente activa, ocupados, desocupados (abiertos y ocultos), inactivos y subempleados (en miles), según sexoTotal Centros poblados y rural disperso',
  18: '%tasa global de participación, de ocupación y desempleo. Ocupados, desocupados e inactivos. (en miles)',
  19: '%tasa global de participación, de ocupación y desempleo. Ocupados, desocupados e inactivos. (en miles)',
  20: 'Población ocupada según posición ocupacional 13 ciudades y áreas metropolitanas',
  21: 'Población ocupada según posición ocupacional Total nacional, cabeceras y resto',
  22: 'Población ocupada según ramas de actividad CIIU 4 A.C 13 ciudades y áreas metropolitanas',
  23: 'Población ocupada según ramas de actividad CIIU 4 A.C Total Nacional, cabeceras y resto',
  24: '% población en edad de trabajar, tasa global de participación, de ocupación, de desempleo (abierto y oculto) y de subempleo. Población total, en edad de trabajar, económicamente activa, ocupados, desocupados (abiertos y ocultos), inactivos y subempleados. 23 ciudades y áreas metropolitanas',
  25: '% población en edad de trabajar, tasa global de participación, de ocupación, de desempleo (abierto y oculto) y de subempleo. Población total, en edad de trabajar, económicamente activa, ocupados, desocupados (abiertos y ocultos), inactivos y subempleados. Total Nacional, cabeceras y resto',
  26: '% población en edad de trabajar, tasa global de participación, de ocupación, de desempleo (abierto y oculto) y de subempleo. Población total, en edad de trabajar, económicamente activa, ocupados, desocupados (abiertos y ocultos), inactivos y subempleados. Total Nacional'},
 'Notas DANE': {0: 'Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo No informa al 5%, que es el nivel de calidad admisible para el DANE. Nota: CIIU Rev 4 se empieza a publicar a partir de enero de 2020. Sin embargo, se pueden obtener resultados desde enero del 2015, ya que se hizo un ejercicio paralelo de codificación de ramas de actividad económica hasta diciembre de 2019. Nota: Datos expandidos con las proyecciones de población elaboradas, con base en los resultados del censo 2005 Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de informalidad de los meses de marzo y abril de 2020. A partir de mayo de 2020, se recolectan nuevamente las variables que permiten obtener datos e indicadores de informalidad.  La publicación del anexo se retoma desde el  trimestre móvil mayo - julio 2020.',
  1: 'Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo No informa al 5%, que es el nivel de calidad admisible para el DANE.  Nota: Datos expandidos con las proyecciones de población elaboradas, con base en los resultados del censo 2005 Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de informalidad de los meses de marzo y abril de 2020. A partir de mayo de 2020, se recolectan nuevamente las variables que permiten obtener datos e indicadores de informalidad.  La publicación del anexo se retoma desde el  trimestre móvil mayo - julio 2020. Nota*: Para los meses de abril y abril de 2020 las cifras son estimadas a partir de los resultados preliminares divulgados en agosto de 2020 replicando la metodología del Registro Estadístico de Relaciones Laborales (RELAB). Este resultado se deriva de un modelo de Random Forest en el que se realiza una nueva calibración de los parámetros con base en la información más reciente de la Gran Encuesta Integrada de Hogares (GEIH). Para mayor información al respecto, puede consultar el siguiente link: https://www.dane.gov.co/files/investigaciones/boletines/ech/ech/Doc_PILA_empleo_imputacion_informalidad_abril_abril_20.pdf Nota*: Para el promedio de los trimestres que se vieron afectados por el cambio de formulario, se toman meses recolectados de GEIH y datos de la metodología RELAB. Solo se presentan cifras para total 13 y total 23 ciudades y áreas metropolitanas.',
  2: 'Nota: Datos expandidos con las proyecciones de población elaboradas, con base en los resultados del censo 2005 Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de informalidad de los meses de marzo y abril de 2020. A partir de mayo de 2020, se recolectan nuevamente las variables que permiten obtener datos e indicadores de informalidad.  La publicación del anexo se retoma desde el  trimestre móvil mayo - julio 2020.',
  3: 'Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo No informa al 5%, que es el nivel de calidad admisible para el DANE. Nota: Datos expandidos con las proyecciones de población elaboradas, con base en los resultados del censo 2005 Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de informalidad de los meses de marzo y abril de 2020. A partir de mayo de 2020, se recolectan nuevamente las variables que permiten obtener datos e indicadores de informalidad.  La publicación del anexo se retoma desde el  trimestre móvil mayo - julio 2020.',
  4: 'Nota: Datos expandidos con las proyecciones de población elaboradas, con base en los resultados del censo 2005 Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de informalidad de los meses de marzo y abril de 2020. A partir de mayo de 2020, se recolectan nuevamente las variables que permiten obtener datos e indicadores de informalidad.  La publicación del anexo se retoma desde el  trimestre móvil mayo - julio 2020.',
  5: 'Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo No informa al 5%, que es el nivel de calidad admisible para el DANE. Nota: Datos expandidos con las proyecciones de población elaboradas, con base en los resultados del censo 2005 Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de informalidad de los meses de marzo y abril de 2020. A partir de mayo de 2020, se recolectan nuevamente las variables que permiten obtener datos e indicadores de informalidad.  La publicación del anexo se retoma desde el  trimestre móvil mayo - julio 2020.',
  6: 'Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo No informa al 5%, que es el nivel de calidad admisible para el DANE. Nota: Datos expandidos con las proyecciones de población elaboradas, con base en los resultados del censo 2005 Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de informalidad de los meses de marzo y abril de 2020. A partir de mayo de 2020, se recolectan nuevamente las variables que permiten obtener datos e indicadores de informalidad.  La publicación del anexo se retoma desde el  trimestre móvil mayo - julio 2020.',
  7: 'Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo No informa al 5%, que es el nivel de calidad admisible para el DANE.  Nota: Datos expandidos con las proyecciones de población elaboradas, con base en los resultados del censo 2005 Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de informalidad de los meses de marzo y abril de 2020. A partir de mayo de 2020, se recolectan nuevamente las variables que permiten obtener datos e indicadores de informalidad.  La publicación del anexo se retoma desde el  trimestre móvil mayo - julio 2020. Nota*: Para los meses de abril y abril de 2020 las cifras son estimadas a partir de los resultados preliminares divulgados en agosto de 2020 replicando la metodología del Registro Estadístico de Relaciones Laborales (RELAB). Este resultado se deriva de un modelo de Random Forest en el que se realiza una nueva calibración de los parámetros con base en la información más reciente de la Gran Encuesta Integrada de Hogares (GEIH). Para mayor información al respecto, puede consultar el siguiente link: https://www.dane.gov.co/files/investigaciones/boletines/ech/ech/Doc_PILA_empleo_imputacion_informalidad_abril_abril_20.pdf Nota*: Para el promedio de los trimestres que se vieron afectados por el cambio de formulario, se toman meses recolectados de GEIH y datos de la metodología RELAB. Solo se presentan cifras para total 13 y total 23 ciudades y áreas metropolitanas.',
  8: 'Nota: Datos expandidos con proyecciones de población, elaborados con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de subempleo entre los meses de marzo y julio de 2020. ',
  9: 'Nota: Datos expandidos con proyecciones de población, elaborados con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota*: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de subempleo entre los meses de marzo y julio de 2020. ',
  10: 'Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota: Resultados en miles. Por efecto del redondeo en miles, los totales pueden diferir ligeramente Otros: incapacitado permanente para trabajar, rentista, pensionado, jubilado, personas que no les llama la atención o creen que no vale la pena trabajar',
  11: 'Nota: cifras preliminares debido al método de estimación. Las series pueden ser modificadas al incorporarse nueva información.',
  12: 'Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005.Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE.Nota: Resultados en miles. Por efecto del redondeo en miles, los totales pueden diferir ligeramente * Incluye trabajadores familiares sin remuneración en empresas o negocios de otros hogares apartir de agosto de 2006.',
  13: 'Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005.Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE.Nota: Resultados en miles. Por efecto del redondeo en miles, los totales pueden diferir ligeramenteNota: Ramas de actividad según CIIU 4 Rev. A.C. ',
  14: 'Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005.Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE.Nota: Resultados en miles. Por efecto del redondeo en miles, los totales pueden diferir ligeramenteNota: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de subempleo en los meses de marzo, abril, mayo, junio y julio de 2020.',
  15: 'Nota: cifras preliminares debido al método de estimación. Las series pueden ser modificadas al incorporarse nueva información.',
  16: 'Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005.Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE.Nota: Resultados en miles. Por efecto del redondeo en miles, los totales pueden diferir ligeramenteNota: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de subempleo en los meses de marzo, abril, mayo, junio y julio de 2020. ',
  17: 'Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005.Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE.Nota: Resultados en miles. Por efecto del redondeo en miles, los totales pueden diferir ligeramenteNota: Debido al cambio en el operativo de recolección de la GEIH por la pandemia del COVID-19, no fue posible obtener información de subempleo en los meses de marzo, abril, mayo, junio y julio de 2020. ',
  18: 'Nota: cifras preliminares debido al método de estimación. Las series pueden ser modificadas al incorporarse nueva información.',
  19: 'Nota: cifras preliminares debido al método de estimación. Las series pueden ser modificadas al incorporarse nueva información.',
  20: 'Nota: A partir de julio de 2006, inicia la Gran Encuesta Integrada de Hogares Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota: CIIU Rev 4 se empieza a publicar a partir de enero de 2020. Sin embargo, se pueden obtener resultados desde enero del 2015, ya que se hizo un ejercicio paralelo de codificación de ramas de actividad económica hasta diciembre de 2019. ',
  21: 'Nota: A partir de julio de 2006, inicia la Gran Encuesta Integrada de Hogares Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota: CIIU Rev 4 se empieza a publicar a partir de enero de 2020. Sin embargo, se pueden obtener resultados desde enero del 2015, ya que se hizo un ejercicio paralelo de codificación de ramas de actividad económica hasta diciembre de 2019. ',
  22: 'Nota: A partir de julio de 2006, inicia la Gran Encuesta Integrada de Hogares Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota: CIIU Rev 4 se empieza a publicar a partir de enero de 2020. Sin embargo, se pueden obtener resultados desde enero del 2015, ya que se hizo un ejercicio paralelo de codificación de ramas de actividad económica hasta diciembre de 2019. ',
  23: 'Nota: A partir de julio de 2006, inicia la Gran Encuesta Integrada de Hogares Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota: CIIU Rev 4 se empieza a publicar a partir de enero de 2020. Sin embargo, se pueden obtener resultados desde enero del 2015, ya que se hizo un ejercicio paralelo de codificación de ramas de actividad económica hasta diciembre de 2019. ',
  24: 'Nota: A partir de julio de 2006, inicia la Gran Encuesta Integrada de Hogares Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota: CIIU Rev 4 se empieza a publicar a partir de enero de 2020. Sin embargo, se pueden obtener resultados desde enero del 2015, ya que se hizo un ejercicio paralelo de codificación de ramas de actividad económica hasta diciembre de 2019. ',
  25: 'Nota: A partir de julio de 2006, inicia la Gran Encuesta Integrada de Hogares Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota: CIIU Rev 4 se empieza a publicar a partir de enero de 2020. Sin embargo, se pueden obtener resultados desde enero del 2015, ya que se hizo un ejercicio paralelo de codificación de ramas de actividad económica hasta diciembre de 2019. ',
  26: 'Nota: A partir de julio de 2006, inicia la Gran Encuesta Integrada de Hogares Nota: Datos expandidos con proyecciones de población, elaboradas con base en los resultados del censo 2005. Nota: Toda variable cuya proporción respecto a la PEA sea menor al 10%, tiene un error de muestreo superior al 5%, que es el nivel de calidad admisible para el DANE. Nota: CIIU Rev 4 se empieza a publicar a partir de enero de 2020. Sin embargo, se pueden obtener resultados desde enero del 2015, ya que se hizo un ejercicio paralelo de codificación de ramas de actividad económica hasta diciembre de 2019. '},
 'Fuente': {0: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-informal-y-seguridad-social',
  1: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-informal-y-seguridad-social',
  2: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-informal-y-seguridad-social',
  3: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-informal-y-seguridad-social',
  4: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-informal-y-seguridad-social',
  5: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-informal-y-seguridad-social',
  6: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-informal-y-seguridad-social',
  7: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-informal-y-seguridad-social',
  8: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/por-regiones',
  9: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/por-regiones',
  10: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/segun-sexo',
  11: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/segun-sexo',
  12: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/segun-sexo',
  13: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/segun-sexo',
  14: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/segun-sexo',
  15: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/segun-sexo',
  16: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/segun-sexo',
  17: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/segun-sexo',
  18: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo',
  19: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo',
  20: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo',
  21: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo',
  22: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo',
  23: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo',
  24: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo',
  25: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo',
  26: 'https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo'}}
    
    return pd.DataFrame(f)